### ISSUE TITLE
how can i use webpagetest to analyse result.json?

### ISSUE THREAD

**Issue by qileilove** [ivangabriele/gulp-webpagetest#1]
hi ivangabriele,
this tool is very useful. but the output json file seems to  be hard to understand， how can i use other tools to  analyse the json file or use the json to generate some chart，help other people easy to know.

**Comment by ivangabriele** [comment]
Hi !

I already developed a tool for my company able to extract only specified data from the output to generate simpler JSON files, merge them as an "timelined" array, and chart them in live using via an AngularJS application using the [ng-chartists](http://angular-js.in/ng-chartist-js/) module.

Excepted the front application for chart, I could integrate the 2 first features as an option to make it more useful. About how to chart them, it's really up to you. I can recommend you tu use one of these three chart tools :

- [Chartist](https://gionkunz.github.io/chartist-js/) **simple and beautiful**
- [Chart.js](http://www.chartjs.org/) **more complex but very cutomizable**
- [Google Chart](https://developers.google.com/chart/) **quite more complex but powerful**

**Comment by qileilove** [comment]
Yeah,what you say is very great,  I found another  package support to generate the report，it's webpagetest-mapper,but it isn't a gulp package.
